#!/usr/bin/env bash
set -euo pipefail
project_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cmake -S "$project_dir" -B "$project_dir/build" -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo
cmake --build "$project_dir/build" -j 3
exec "$project_dir/build/omaframe" "$@"
